language: go
go: "1.10"

services:
- docker

before_script:
- go get -u github.com/golang/dep/cmd/dep


jobs:
  include:
  - stage: Build Image
    name: build kubevirt-node-labeller image
    script: make image 
    deploy:
      provider: script
      skip_cleanup: true
      before_script: docker login -u="$NFDNAME" -p="$NFDPASS" quay.io
      script: make push-image
      on:
        branch: master
        tags: true


