language: go
go: "1.10"

services:
- docker

before_script:
- go get -u github.com/golang/dep/cmd/dep


jobs:
  include:
  - stage: Build Image
    name: build node-labeller image
    script: make image 
    deploy:
      before_script: 
      - echo "$NFDPASS" | docker login -u="$NFDNAME" quay.io --password-stdin
      provider: script
      skip_cleanup: true
      script: make push-image
      on:
        branch: master
        tags: true


