---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  vars_files: "{{ playbook_dir }}/ansible_vars/vars.yaml"
  tasks:
  - name: Prepare release directory
    file:
      path: "{{ playbook_dir }}/_out"
      state: directory
  - name: Generate deploy manifest
    template:
      src: "{{ playbook_dir }}/deploy-templates/roles.yaml"
      dest: "{{ playbook_dir }}/_out/roles.yaml"
  - name: Generate deploy manifest
    template:
      src: "{{ playbook_dir }}/deploy-templates/node-labeller-ds.yaml"
      dest: "{{ playbook_dir }}/_out/node-labeller-ds.yaml"


