---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-labeller
  name: node-labeller
spec:
  selector:
    matchLabels:
      app: node-labeller
  template:
    metadata:
      labels:
        app: node-labeller
    spec:
      serviceAccount: node-labeller
      containers:
      - name: node-labeller-sleeper
        image: "quay.io/kubevirt/node-labeller:v0.1.0"
        command: ["sleep"]
        args: ["infinity"]
      initContainers:
        - image: "quay.io/fromani/kvm-info-nfd-plugin:v0.5.4"
          command: ["/bin/sh","-c"]
          args: ["cp /usr/bin/kvm-caps-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/;"]
          imagePullPolicy: Always
          name: kvm-info-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
  
        - image: "quay.io/kubevirt/cpu-nfd-plugin:v0.1.0"
          command: ["/bin/sh","-c"]
          args: ["cp /plugin/dest/cpu-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/; cp /config/cpu-plugin-configmap.yaml /etc/kubernetes/node-feature-discovery/source.d/cpu-plugin-configmap.yaml;"]
          imagePullPolicy: Always
          name: cpu-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
            - mountPath: /config
              name: cpu-config

        - image: "kubevirt/virt-launcher:v0.17.0"
          command: ["/bin/sh","-c"]
          args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities --machine q35 --arch x86_64 --virttype kvm > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml; cp -r /usr/share/libvirt/cpu_map /etc/kubernetes/node-feature-discovery/source.d/"]
          imagePullPolicy: Always
          name: libvirt
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          name: node-labeller
          image: "quay.io/kubevirt/node-labeller:v0.1.0"
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"

      volumes:
        - name: nfd-source
          emptyDir: {}
        - name: cpu-config
          configMap:
            name: cpu-plugin-configmap
