apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-node-labeller
  namespace: "{{ namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: "{{ namespace }}"
  name: kubevirt-node-labeller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - patch
  - update
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubevirt-node-labeller
allowPrivilegedContainer: true
runAsUser: 
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:{{ namespace }}:kubevirt-node-labeller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-node-labeller
subjects:
- kind: ServiceAccount
  name: kubevirt-node-labeller
  namespace: "{{ namespace }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-cpu-plugin-configmap
  namespace: "{{ namespace }}"
data:
  cpu-plugin-configmap.yaml: |- 
    obsoleteCPUs:
      - "486"
      - "pentium"
      - "pentium2"
      - "pentium3"
      - "pentiumpro"
      - "coreduo"
      - "n270"
      - "core2duo"
      - "Conroe"
      - "athlon"
      - "phenom"
    minCPU: "Penryn"
